name: lifecare_connect
description: Test CHW login screen only
version: 1.0.0+1
publish_to: "none"

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  # ✅ Firebase Core & Auth
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.4
  firebase_app_check: ^0.2.2+7
  firebase_messaging: ^14.7.3
  firebase_storage: ^11.6.0
  firebase_analytics: ^10.10.0
  cloud_firestore: ^4.14.0

  # ✅ Notifications
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2

  # ✅ Navigation
  go_router: ^13.2.1

  # ✅ Social Auth
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^6.0.2

  # ✅ Utilities
  image_picker: ^1.0.7
  shared_preferences: ^2.2.2
  file_picker: ^8.0.7
  geolocator: ^12.0.0
  connectivity_plus: ^6.1.4
  intl: ^0.19.0
  table_calendar: ^3.1.3
  video_player: ^2.8.6
  just_audio: ^0.9.36
  url_launcher: ^6.3.2
  syncfusion_flutter_pdfviewer: ^27.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # ✅ Add assets folder if you use images or fonts
  # assets:
  #   - assets/images/
  #   - assets/audio/
