import 'package:flutter/material.dart';

class PrivacyScreen extends StatelessWidget {
  const PrivacyScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Privacy Policy'),
        backgroundColor: Colors.teal,
        foregroundColor: Colors.white,
      ),
      body: Padding(
        padding: const EdgeInsets.all(20.0),
        child: SingleChildScrollView(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text('LifeCare Connect – Privacy Policy', style: TextStyle(fontSize: 22, fontWeight: FontWeight.bold, color: Colors.teal)),
              SizedBox(height: 8),
              Text('Effective Date: August 5, 2025', style: TextStyle(fontSize: 14, color: Colors.grey[700])),
              Text('Developed by Rural Health Mission Nigeria', style: TextStyle(fontSize: 14, color: Colors.grey[700])),
              SizedBox(height: 18),
              Text('Introduction', style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold, color: Colors.teal)),
              SizedBox(height: 6),
              Text('Welcome to LifeCare Connect. We are committed to protecting your personal information and ensuring transparency in how we collect, use, and secure your data. This privacy policy explains our practices in line with app store requirements and user-friendly transparency.', style: TextStyle(fontSize: 16)),
              SizedBox(height: 18),
              Text('Data We Collect', style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold, color: Colors.teal)),
              SizedBox(height: 6),
              Text('We collect only the data necessary to deliver healthcare services effectively:', style: TextStyle(fontSize: 16)),
              SizedBox(height: 8),
              Text('• Personal information: name, email address, phone number, user ID, and address', style: TextStyle(fontSize: 16)),
              Text('• Health information: antenatal/postnatal visits, referrals, prescriptions, and lab results', style: TextStyle(fontSize: 16)),
              Text('• Financial data: payment info, purchase history, credit score (if applicable)', style: TextStyle(fontSize: 16)),
              Text('• Location data: approximate location only', style: TextStyle(fontSize: 16)),
              Text('• Messages: in-app chats, emails', style: TextStyle(fontSize: 16)),
              Text('• Device and app usage: errors, features used, performance', style: TextStyle(fontSize: 16)),
              SizedBox(height: 18),
              Text('Why We Collect This Data', style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold, color: Colors.teal)),
              SizedBox(height: 6),
              Text('We use your data to:', style: TextStyle(fontSize: 16)),
              SizedBox(height: 8),
              Text('• Deliver healthcare services and consultations', style: TextStyle(fontSize: 16)),
              Text('• Facilitate referrals, prescriptions, and health records', style: TextStyle(fontSize: 16)),
              Text('• Schedule visits and send SMS/WhatsApp reminders', style: TextStyle(fontSize: 16)),
              Text('• Manage user accounts and secure app access', style: TextStyle(fontSize: 16)),
              Text('• Troubleshoot issues and improve app features', style: TextStyle(fontSize: 16)),
              Text('• Send important communications', style: TextStyle(fontSize: 16)),
              Text('• Ensure fraud prevention and legal compliance', style: TextStyle(fontSize: 16)),
              SizedBox(height: 18),
              Text('How We Handle Your Data', style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold, color: Colors.teal)),
              SizedBox(height: 6),
              Text('• All data is encrypted in transit and at rest (HTTPS, AES)', style: TextStyle(fontSize: 16)),
              Text('• Stored securely using Google Cloud and Firebase', style: TextStyle(fontSize: 16)),
              Text('• Access is restricted to authorized healthcare workers and supervisors', style: TextStyle(fontSize: 16)),
              Text('• We do not sell or share data with advertisers or third parties', style: TextStyle(fontSize: 16)),
              SizedBox(height: 18),
              Text('Offline Usage', style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold, color: Colors.teal)),
              SizedBox(height: 6),
              Text('LifeCare Connect works offline. Your data is stored on your device and securely synced once you\'re online.', style: TextStyle(fontSize: 16)),
              SizedBox(height: 18),
              Text('Your Rights & Controls', style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold, color: Colors.teal)),
              SizedBox(height: 6),
              Text('You have full control over your information. You can:', style: TextStyle(fontSize: 16)),
              Text('• View and edit your personal data', style: TextStyle(fontSize: 16)),
              Text('• Opt out of providing optional data (like email address)', style: TextStyle(fontSize: 16)),
              Text('• Delete your account and data permanently', style: TextStyle(fontSize: 16)),
              SizedBox(height: 18),
              Text('How to Delete Your Account', style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold, color: Colors.teal)),
              SizedBox(height: 6),
              Text('To permanently delete your account:', style: TextStyle(fontSize: 16)),
              Text('• Open the app', style: TextStyle(fontSize: 16)),
              Text('• Go to Settings > Account > Delete Account', style: TextStyle(fontSize: 16)),
              Text('• Confirm deletion', style: TextStyle(fontSize: 16)),
              Text('All your personal and health data will be permanently removed.', style: TextStyle(fontSize: 16)),
              SizedBox(height: 18),
              Text('Changes to This Policy', style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold, color: Colors.teal)),
              SizedBox(height: 6),
              Text('We may update this privacy policy occasionally. If we do, you’ll be notified within the app.', style: TextStyle(fontSize: 16)),
              SizedBox(height: 18),
              Text('Contact Us', style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold, color: Colors.teal)),
              SizedBox(height: 6),
              Text('If you have questions, feedback, or complaints, reach out to us:', style: TextStyle(fontSize: 16)),
              Text('contact_lifecare@rhemn.org.ng', style: TextStyle(fontSize: 16, color: Colors.teal, fontWeight: FontWeight.bold)),
            ],
          ),
        ),
      ),
    );
  }
}
